### ISSUE TITLE
How to modify the log level of the console?

### ISSUE THREAD

**Issue by KonradHoeffner** [openlink/virtuoso-opensource#1061]
Using `ErrorLogLevel` in `virtuoso.ini`, I can change the verbosity of `virtuoso.log`. However it does not have any effect on the console and thus on the Docker / Docker compose log. How can I set the error log level for the console instead or in addition to the log file?

**Comment by pkleef** [comment]
The OpenLink docker images run Virtuoso with the `+foreground` flag which will make sure virtuoso does not spawn itself into the background. It also creates a secondary log channel to `stderr` where all log messages up to and including `DEBUG` log messages are  shown.

There are additional functions in the Virtuoso Procedure Language (PL) such as [`dbg_printf()`](http://docs.openlinksw.com/virtuoso/fn_dbg_printf/) and [`dbg_obj_print()`](http://docs.openlinksw.com/virtuoso/fn_dbg_obj_print/) which are extremely useful for debugging stored procedures in both VAD packages and embedded PL in the Virtuoso Engine itself. These functions also print to the `stderr` channel.

By default both `docker` and `docker-compose` commands capture all the output from both the `stdout` and `stderr` channels of the running application. 

When running your docker image in attached mode using either `docker run -i -t .....`, `docker create -i -t`, or `docker-compose up` all these messages are shown on your terminal.

Removing the `-i -t` flags to the regular `docker` commands will not show these messages as it detaches the docker instance from your terminal. Similarly, using the 'docker-compose up -d` command does the same thing for Docker Compose. 

Of course should you need to check the log for the Virtuoso docker instance, you can still use the command:
```
$ docker logs INSTANCE_NAME
```

Since you are using the `docker-compose` command, you can also modify your `docker-compose.yml` script to completely disable any logging from the Virtuoso docker instance by adding a <code>logging</code> section . This may come in handy if you are trying to debug the interaction between multiple services in the same `docker-compose.yml` and want reduce the amount of log lines to examine:

```
version: "3.3"
services:
  virtuoso:
    image: openlink/virtuoso-opensource-7
    logging:
      driver: none
    environment:
      - DBA_PASSWORD=${DBA_PASSWORD}
      - VIRTUOSO_INI_FILE=/ini/virtuoso.ini
    volumes:
      - ./ontology:/database/data                      
      - ./virtuoso/ini:/ini    
      - ./virtuoso/sql:/opt/virtuoso-opensource/initdb.d
      [...]
```
 
 This will completely disable all logging as in:
 ```
 $ docker-compose up
Starting example_virtuoso_1 ... done
Attaching to example_virtuoso_1
virtuoso_1  | WARNING: no logs are available with the 'none' log driver
``` 

However we do not recommend running with this option set by default, as it can make it difficult to debug issues with the Virtuoso docker instance itself
