### ISSUE TITLE
Virtuoso gradually saturate resources until it crashes

### ISSUE THREAD

**Issue by mhoangvslev** [openlink/virtuoso-opensource#1110]
In the `compose` file, I set these params:

```yaml
bsbm-virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.7
    environment:
      SPARQL_UPDATE: "false"
      DBA_PASSWORD: "dba"
      VIRT_HTTPServer_ServerThreads: 20
      VIRT_HTTPServer_MaxClientConnections: 20
      VIRT_SPARQL_MaxQueryCostEstimationTime: 0
      VIRT_SPARQL_ResultSetMaxRows: 0
      VIRT_SPARQL_MaxQueryExecutionTime: 0
      VIRT_Parameters_NumberOfBuffers: 1360000
      VIRT_Parameters_MaxDirtyBuffers: 1000000
      VIRT_Parameters_ThreadCleanupInterval: 10
      VIRT_Parameters_ResourcesCleanupInterval: 10
      VIRT_Parameters_MaxClientConnections: 20
      VIRT_Parameters_IndexTreeMaps: 256
      VIRT_Plugins_Load1: "plain, geos"
      VIRT_Plugins_Load2: "plain, proj4"
      VIRT_Plugins_Load3: "plain, shapefileio"
      #VIRT_Plugins_Load4: "plain, graphql"
    volumes:
      #- "../model/dataset:/usr/local/virtuoso-opensource/share/virtuoso/vad"
      - "../model/dataset:/usr/share/proj"
    ports:
      - 33201-33210:1111
      - 34201-34210:8890
```

- I launch rdf4j's FedX to evaluate queries sequentially. After each launch, I force-kill every "FedX" process with `pkill -9 -f "FedX"` because for some reason FedX left dangling children processes. But even with FedX processes killed, I still observe a large amount of RAM consumption coming from Virtuoso. 
- I also notice in the log `Monitor: No Web Server threads available, ServerThreads in [HTTP Server] may have to be increased` as in #908.
