### ISSUE TITLE
SPARQL query causes Virtuoso to crash without log

### ISSUE THREAD

**Issue by l-ellenbeck** [openlink/virtuoso-opensource#1301]
We are running virtuoso in a container.
In a default container, without any modification and the basic settings, running the following query crashes the container in the version `virtuoso-opensource-7:7.2.12` and `virtuoso-opensource-7:7.2.13`

```sparql
SELECT ?g ?m WHERE {                
  GRAPH <https://purl.org/xxxx/resources/a5c139eb-d3fe-4ca6-8685-f81947063677> {
      <https://purl.org/xxxx/resources/a5c139eb-d3fe-4ca6-8685-f81947063677> <http://www.w3.org/ns/dcat#catalog> ?g .
  }
  
  GRAPH ?g{
      ?g a <http://purl.org/fdp/fdp-o#MetadataService> .
      ?g <http://purl.org/fdp/fdp-o#hasMetadata> ?m .
  }
  
  GRAPH ?m {
      ?m <http://purl.org/fdp/fdp-o#hasMetadata> ?version .
  }
}
```
The query is a minimal example, as the original is more complex (and also fails).

This query worked and still works in the container version `virtuoso-opensource-7:7.2.11`.
This seems to be a regression in capabilities.

Most concerning is, that we don't get any log entry from Virtuoso.
The written logs and logs of the container itself just end with the immediate termination of the container.
The crash appears to be instant and was reproduced on a separate machine.

We use Rocky 9 Linux and podman and podman-compose in the newest version 

Here is the relevant compose entry:
```yaml
  virtuoso:
    image: docker.io/openlink/virtuoso-opensource-7:7.2.12
    userns_mode: host
    environment:
      DBA_PASSWORD: dba
    volumes:
      - ./.data/virtuoso/:/database
      - ./.config/virtuoso/virtuoso.ini:/database/virtuoso.ini
```

The `virtuoso.ini` was in default settings and with extended bytes and had no effect.
